"""initial schema

Revision ID: 709600d2e2b1
Revises: 
Create Date: 2026-08-21 20:45:06.106429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709600d2e2b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact_channel', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_cases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('failure_category', sa.String(), nullable=True),
    sa.Column('error_source', sa.String(), nullable=True),
    sa.Column('error_step', sa.String(), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('revenue_case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_case_id'], ['revenue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('revenue_case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_case_id'], ['revenue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('revenue_case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chosen_action', sa.String(), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('guardrails_applied', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_case_id'], ['revenue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_cases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('revenue_case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('arm', sa.String(), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contacts_made', sa.Integer(), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=True),
    sa.Column('hours_to_recovery', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_case_id'], ['revenue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('revenue_case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('razorpay_event_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_case_id'], ['revenue_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_event_id')
    )
    op.create_table('promises_to_pay',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('revenue_case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('promised_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promised_date', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revenue_case_id'], ['revenue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('revenue_case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('decision_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['revenue_case_id'], ['revenue_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    op.drop_table('promises_to_pay')
    op.drop_table('payment_events')
    op.drop_table('experiment_cases')
    op.drop_table('decisions')
    op.drop_table('customer_messages')
    op.drop_table('audit_events')
    op.drop_table('revenue_cases')
    op.drop_table('customers')
    # ### end Alembic commands ###
